name: Discord Notify

on:
  schedule:
    - cron: '0 3 * * 1-5' # UTC 기준 매일 03:00 (한국 시간 12:00)
  workflow_dispatch: # 수동 실행 가능

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃 소스
        uses: actions/checkout@v3

      - name: Python 셋업
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 디스코드 알림 실행
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python discord_notify.py
