name: Discord Notify

on:
  schedule:
    - cron: '0 12 * * 1-5'  # 매주 월~금 12:00 정각에 실행 (UTC 기준)
  workflow_dispatch:        # 수동 실행도 가능하게

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Send Discord Notification
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python -c "
import requests
from datetime import datetime

WEBHOOK_URL = '${{ env.WEBHOOK_URL }}'

now = datetime.now()
weekday = now.weekday()

message = {
    'content': f'✨[자동화된 채팅입니다]✨\n{now.strftime('%Y-%m-%d')} 스터디 끝! 다들 맛점심하시길... \n오늘 한 내용 내용공유방에 올리기!\n ~정세영 올림~'
}

if weekday < 5:
    response = requests.post(WEBHOOK_URL, json=message)
    if response.status_code == 204:
        print('디스코드로 메시지 전송 성공')
    else:
        print(f'전송 실패: {response.status_code} - {response.text}')
else:
    print('오늘은 평일이 아니므로 메시지를 보내지 않습니다.')
"
